export const mealMock = {
  meals: [{
    idMeal: '52771',
    strMeal: 'Spicy Arrabiata Penne',
    strCategory: 'Vegetarian',
    strArea: 'Italian',
    strInstructions: 'Cook the pasta in a pan',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
    strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
    strIngredient1: 'Penne Rigate',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Garlic',
    strIngredient4: 'Red Chilli',
    strIngredient5: 'Italian Tomatoes',
    strIngredient6: 'Dried Oregano',
    strIngredient7: 'Red Wine',
    strIngredient8: 'Fresh Basil',
    strIngredient9: 'Salt',
    strIngredient10: 'Black Pepper',
    strIngredient11: 'Parmesan',
    strIngredient12: 'Water',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 pound',
    strMeasure2: '1/4 cup',
    strMeasure3: '1 clove',
    strMeasure4: '1',
    strMeasure5: '1 tin',
    strMeasure6: '1 teaspoon',
    strMeasure7: '1/2 cup',
    strMeasure8: '6 leaves',
    strMeasure9: 'to taste',
    strMeasure10: 'to taste',
    strMeasure11: 'to taste',
    strMeasure12: '1/2 cup',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
  }] };
